export type PortraitKind = "life_portrait" | "contemporary_depiction" | "posthumous_historical_depiction";

export interface PortraitSource {
  portrait: string;
  portraitTitle: string;
  portraitCreator: string;
  portraitDate: string;
  portraitInstitution: string;
  portraitSource: string;
  portraitKind: PortraitKind;
  portraitKindLabel: string;
  portraitNote: string;
  portraitRights: string;
}

export const portraitSources: Record<string, PortraitSource> = {
  "george-washington": {
    portrait: "https://files.manuscdn.com/user_upload_by_module/session_file/90544947/WrAXkxEVfhSStaBC.webp",
    portraitTitle: "George Washington (Vaughan-Sinclair portrait)",
    portraitCreator: "Gilbert Stuart (American, 1755–1828)",
    portraitDate: "1795",
    portraitInstitution: "National Gallery of Art, Washington, DC (Andrew W. Mellon Collection; accession 1940.1.6)",
    portraitSource: "https://www.nga.gov/artworks/565-george-washington-vaughan-sinclair-portrait",
    portraitKind: "life_portrait",
    portraitKindLabel: "Life portrait",
    portraitNote: "Authenticated portrait created during George Washington’s lifetime.",
    portraitRights: "The National Gallery of Art object page explicitly states that this object's media is free and in the public domain. Its Open Access policy states that downloadable images are free for commercial and noncommercial use.",
  },
  "benjamin-franklin": {
    portrait: "https://files.manuscdn.com/user_upload_by_module/session_file/90544947/hXYzBLvdUXtdmLKw.webp",
    portraitTitle: "Benjamin Franklin",
    portraitCreator: "Joseph Siffred Duplessis (1725–1802)",
    portraitDate: "c. 1785",
    portraitInstitution: "Smithsonian National Portrait Gallery, Washington, D.C. (NPG.87.43)",
    portraitSource: "https://commons.wikimedia.org/wiki/File:Joseph_Siffrein_Duplessis_-_Benjamin_Franklin_-_Google_Art_Project.jpg",
    portraitKind: "life_portrait",
    portraitKindLabel: "Life portrait",
    portraitNote: "Authenticated portrait created during Benjamin Franklin’s lifetime.",
    portraitRights: "The Commons source identifies this as a faithful photographic reproduction of Duplessis’s two-dimensional public-domain painting; Duplessis died in 1802, and Commons marks the digital file Public Domain Mark/PD-Art. The Smithsonian object record licenses its media CC0.",
  },
  "john-adams": {
    portrait: "https://files.manuscdn.com/user_upload_by_module/session_file/90544947/nNsfJRqspsUaSkMv.webp",
    portraitTitle: "John Adams",
    portraitCreator: "John Trumbull (1756–1843)",
    portraitDate: "1793",
    portraitInstitution: "National Portrait Gallery, Smithsonian Institution, Washington, D.C. (accession NPG.75.52)",
    portraitSource: "https://commons.wikimedia.org/wiki/File:John_Trumbull_-_John_Adams_-_Google_Art_Project.jpg",
    portraitKind: "life_portrait",
    portraitKindLabel: "Life portrait",
    portraitNote: "Authenticated portrait created during John Adams’s lifetime.",
    portraitRights: "The painting is public domain: Trumbull died in 1843 (more than 100 years ago), and the Commons file page identifies it as a faithful photographic reproduction of a two-dimensional public-domain work (CC-PD-Mark/PD-Art). The Smithsonian object record also marks its media CC0. The Commons digital file was sourced from Google Cultural Institute maximum-zoom imagery.",
  },
  "thomas-jefferson": {
    portrait: "https://files.manuscdn.com/user_upload_by_module/session_file/90544947/YmaQIefiIkhSfrEh.webp",
    portraitTitle: "Thomas Jefferson",
    portraitCreator: "Gilbert Stuart (American, 1755–1828)",
    portraitDate: "c. 1821",
    portraitInstitution: "National Gallery of Art, Washington, DC (accession 1986.71.1)",
    portraitSource: "https://www.nga.gov/artworks/69391-thomas-jefferson",
    portraitKind: "life_portrait",
    portraitKindLabel: "Life portrait",
    portraitNote: "Authenticated portrait created during Thomas Jefferson’s lifetime.",
    portraitRights: "The National Gallery of Art’s object page expressly states that this object’s media is free and in the public domain under its Open Access policy. The verified NGA IIIF download is a 3344 × 4096 JPEG.",
  },
  "alexander-hamilton": {
    portrait: "https://files.manuscdn.com/user_upload_by_module/session_file/90544947/GtyAdkagbBXaNWtf.webp",
    portraitTitle: "Alexander Hamilton",
    portraitCreator: "John Trumbull (American, 1756–1843)",
    portraitDate: "c. 1792",
    portraitInstitution: "National Gallery of Art, Washington, D.C. (accession no. 1952.1.1; Gift of the Avalon Foundation)",
    portraitSource: "https://www.nga.gov/artworks/41579-alexander-hamilton",
    portraitKind: "life_portrait",
    portraitKindLabel: "Life portrait",
    portraitNote: "Authenticated portrait created during Alexander Hamilton’s lifetime.",
    portraitRights: "The National Gallery of Art identifies this work's downloadable media as free and in the public domain under its Open Access policy. The underlying oil painting dates to c. 1792, and its creator, John Trumbull, died in 1843.",
  },
  "samuel-adams": {
    portrait: "https://files.manuscdn.com/user_upload_by_module/session_file/90544947/BrmrKJvsQiUXGnGw.webp",
    portraitTitle: "Samuel Adams",
    portraitCreator: "John Singleton Copley (American, 1738–1815)",
    portraitDate: "about 1772",
    portraitInstitution: "Museum of Fine Arts, Boston (accession L-R 30.76c; deposited by the City of Boston)",
    portraitSource: "https://collections.mfa.org/objects/30881",
    portraitKind: "life_portrait",
    portraitKindLabel: "Life portrait",
    portraitNote: "Authenticated portrait created during Samuel Adams’s lifetime.",
    portraitRights: "Copley died in 1815, placing the 1772 painting in the public domain. The supplied Wikimedia Commons file is identified as a faithful photographic reproduction of this two-dimensional public-domain work, marked free of known copyright restrictions; its source is credited to the Museum of Fine Arts, Boston.",
  },
  "paul-revere": {
    portrait: "https://files.manuscdn.com/user_upload_by_module/session_file/90544947/vkCrfroqiKYiLSGE.webp",
    portraitTitle: "Paul Revere",
    portraitCreator: "John Singleton Copley (American, 1738–1815)",
    portraitDate: "1768",
    portraitInstitution: "Museum of Fine Arts, Boston (accession 30.781)",
    portraitSource: "https://collections.mfa.org/objects/32401",
    portraitKind: "life_portrait",
    portraitKindLabel: "Life portrait",
    portraitNote: "Authenticated portrait created during Paul Revere’s lifetime.",
    portraitRights: "The 1768 painting is public domain: Copley died in 1815. The supplied 1,841 × 2,223-pixel JPEG is a Wikimedia Commons faithful photographic reproduction of this two-dimensional public-domain work, marked Public Domain Mark / free of known copyright restrictions in the United States.",
  },
  "abigail-adams": {
    portrait: "https://files.manuscdn.com/user_upload_by_module/session_file/90544947/spKbQxtGrojpktkq.webp",
    portraitTitle: "Abigail Smith Adams (Mrs. John Adams)",
    portraitCreator: "Gilbert Stuart",
    portraitDate: "1800/1815",
    portraitInstitution: "National Gallery of Art, Washington, DC (accession 1954.7.2)",
    portraitSource: "https://www.nga.gov/artworks/42934-abigail-smith-adams-mrs-john-adams",
    portraitKind: "life_portrait",
    portraitKindLabel: "Life portrait",
    portraitNote: "Authenticated portrait created during Abigail Adams’s lifetime.",
    portraitRights: "The National Gallery of Art's inspected object page explicitly states that the object media are free and in the public domain under its Open Access policy; the work was painted by Gilbert Stuart (1755–1828) and is also out of copyright by age.",
  },
  "marquis-de-lafayette": {
    portrait: "https://files.manuscdn.com/user_upload_by_module/session_file/90544947/IblTQRUxBWNNqieb.webp",
    portraitTitle: "Marquis De Lafayette",
    portraitCreator: "Ary Scheffer (1795–1858)",
    portraitDate: "c. 1822",
    portraitInstitution: "National Portrait Gallery, Smithsonian Institution, Washington, D.C. (accession NPG.82.150; John Hay Whitney Collection gift)",
    portraitSource: "https://commons.wikimedia.org/wiki/File:Ary_Scheffer_-_Marquis_De_Lafayette_-_NPG.82.150_-_National_Portrait_Gallery.jpg",
    portraitKind: "life_portrait",
    portraitKindLabel: "Life portrait",
    portraitNote: "Authenticated portrait created during Marquis de Lafayette’s lifetime.",
    portraitRights: "The National Portrait Gallery catalog designates the media CC0 1.0/public domain. The underlying 1822 painting is also a historical work by Ary Scheffer (d. 1858).",
  },
  "king-george-iii": {
    portrait: "https://files.manuscdn.com/user_upload_by_module/session_file/90544947/JGZCntBrTDElbhBA.webp",
    portraitTitle: "George III (1738-1820) (RCIN 405307)",
    portraitCreator: "Allan Ramsay (1713–1784)",
    portraitDate: "1761 (commissioned)",
    portraitInstitution: "Royal Collection, cared for by Royal Collection Trust",
    portraitSource: "https://commons.wikimedia.org/wiki/File:Allan_Ramsay_(1713-84)_-_George_III_(1738-1820)_-_RCIN_405307_-_Royal_Collection.jpg",
    portraitKind: "life_portrait",
    portraitKindLabel: "Life portrait",
    portraitNote: "Authenticated portrait created during King George III’s lifetime.",
    portraitRights: "The Commons file page identifies the underlying Allan Ramsay work as public domain because Ramsay died in 1784 (well beyond life + 100 years) and marks the faithful photographic reproduction Public Domain Mark 1.0 / free of known copyright restrictions. The directly verified original is a 1,081 × 1,650 JPEG.",
  },
  "crispus-attucks": {
    portrait: "https://files.manuscdn.com/user_upload_by_module/session_file/90544947/kgxLwqCFwKeoajFb.webp",
    portraitTitle: "Crispus Attucks",
    portraitCreator: "Maker/artist unknown; a c. 1897 half-tone reproduction of a painting (published/copyrighted by W. H. Curd, Chicago, per LOC note)",
    portraitDate: "c. 1897",
    portraitInstitution: "Library of Congress, Prints and Photographs Division",
    portraitSource: "https://www.loc.gov/pictures/item/2004677546/",
    portraitKind: "posthumous_historical_depiction",
    portraitKindLabel: "Later historical depiction",
    portraitNote: "No confirmed lifetime portrait of Crispus Attucks is known. This is a c. 1897 memorial depiction preserved by the Library of Congress.",
    portraitRights: "The Library of Congress record gives the Rights Advisory “No known restrictions on publication.” The print was published c. 1897, so any original U.S. copyright term has expired; the supplied direct LOC JPEG is 806 × 1024 pixels.",
  },
  "patrick-henry": {
    portrait: "https://files.manuscdn.com/user_upload_by_module/session_file/90544947/aLnAqMfXxHjOskBV.webp",
    portraitTitle: "Patrick Henry",
    portraitCreator: "James Barton Longacre (copy after Lawrence Sully)",
    portraitDate: "c. 1835 (after Lawrence Sully’s 1795 life miniature)",
    portraitInstitution: "National Portrait Gallery, Smithsonian Institution",
    portraitSource: "https://npg.si.edu/object/npg_NPG.77.291",
    portraitKind: "posthumous_historical_depiction",
    portraitKindLabel: "Later historical depiction",
    portraitNote: "A posthumous c. 1835 copy after Lawrence Sully's documented 1795 life miniature.",
    portraitRights: "The Smithsonian source page and image metadata designate this media CC0 1.0 / public domain, expressly permitting copying, modification, and distribution without contacting the Smithsonian.",
  },
  "benedict-arnold": {
    portrait: "https://files.manuscdn.com/user_upload_by_module/session_file/90544947/qrCWjrkkROzJCGCz.webp",
    portraitTitle: "Colonel Arnold—who commanded the provincial troops sent against Quebec, through the wilderness of Canada, and was wounded in storming that city, under General Montgomery",
    portraitCreator: "Thomas Hart",
    portraitDate: "26 March 1776",
    portraitInstitution: "Library of Congress, Prints and Photographs Division (digital ID cph.3a39917; Wikimedia Commons original-file delivery)",
    portraitSource: "https://commons.wikimedia.org/wiki/File:Benedict_Arnold_1.jpg",
    portraitKind: "contemporary_depiction",
    portraitKindLabel: "Contemporary depiction",
    portraitNote: "A period mezzotint published in 1776 during Arnold’s lifetime and preserved by the Library of Congress.",
    portraitRights: "Published in London in 1776; the Commons source page identifies it as public domain in the United States because it was published before 1 January 1931, and marks the file Public Domain Mark 1.0. The Commons original HTTPS asset was directly verified: HTTP 200, Content-Type image/jpeg, 161,618 bytes, 1,119 × 1,536 pixels.",
  },
  "mercy-otis-warren": {
    portrait: "https://files.manuscdn.com/user_upload_by_module/session_file/90544947/jswmbIEPPjDJxgmZ.webp",
    portraitTitle: "Mercy Otis Warren (Mrs. James Warren)",
    portraitCreator: "John Singleton Copley (American, 1738–1815)",
    portraitDate: "about 1763",
    portraitInstitution: "Museum of Fine Arts, Boston (accession 31.212; Bequest of Winslow Warren)",
    portraitSource: "https://collections.mfa.org/objects/32409",
    portraitKind: "life_portrait",
    portraitKindLabel: "Life portrait",
    portraitNote: "Authenticated portrait created during Mercy Otis Warren’s lifetime.",
    portraitRights: "The underlying painting was made about 1763 by John Singleton Copley, who died in 1815. The selected Commons reproduction is explicitly marked Public Domain Mark 1.0/free of known copyright restrictions and identifies its source as the MFA, Boston; the direct 1,248 × 1,568 JPEG is a reusable public-domain file.",
  },
  "phillis-wheatley": {
    portrait: "https://files.manuscdn.com/user_upload_by_module/session_file/90544947/lITZvkrEhnZdgoRc.webp",
    portraitTitle: "Phillis Wheatley",
    portraitCreator: "Attributed to Scipio Moorhead (American, active Boston, 1760–75); published by Archibald Bell",
    portraitDate: "1773",
    portraitInstitution: "The Metropolitan Museum of Art, New York (object 49.40.24, The Elisha Whittelsey Collection)",
    portraitSource: "https://www.metmuseum.org/art/collection/search/396463",
    portraitKind: "contemporary_depiction",
    portraitKindLabel: "Contemporary depiction",
    portraitNote: "The principal contemporary depiction of Wheatley: the 1773 frontispiece to her published poems, attributed to Scipio Moorhead.",
    portraitRights: "The Metropolitan Museum of Art marks this object Public Domain; its Open Access policy states that public-domain images are available for unrestricted commercial and noncommercial use. The Met Collection API explicitly reports isPublicDomain: true for object 396463.",
  },
  "baron-von-steuben": {
    portrait: "https://files.manuscdn.com/user_upload_by_module/session_file/90544947/yKrbPdkOWARVrzpk.webp",
    portraitTitle: "Baron Frederick William von Steuben",
    portraitCreator: "Charles Willson Peale (1741–1827)",
    portraitDate: "1780",
    portraitInstitution: "Pennsylvania Academy of the Fine Arts (PAFA), accession no. 1881.1",
    portraitSource: "https://www.pafa.org/museum/collection/item/baron-frederick-william-von-steuben",
    portraitKind: "contemporary_depiction",
    portraitKindLabel: "Contemporary depiction",
    portraitNote: "A named 1780 portrait made during von Steuben’s lifetime; no documented live sitting is claimed.",
    portraitRights: "PAFA's object record states \"No known copyright restrictions.\" The underlying 1780 painting is public domain: Peale died in 1827, and the Wikimedia Commons file is identified as a faithful reproduction of the two-dimensional public-domain work, public domain in the United States because it was published before January 1, 1931.",
  },
  "nathanael-greene": {
    portrait: "https://files.manuscdn.com/user_upload_by_module/session_file/90544947/UrSmkEoaUUSAJzWe.webp",
    portraitTitle: "Nathanael Greene",
    portraitCreator: "Charles Willson Peale",
    portraitDate: "1783",
    portraitInstitution: "Independence National Historical Park, National Park Service (catalog no. INDE 14055)",
    portraitSource: "https://artsandculture.google.com/asset/nathanael-greene-charles-willson-peale-from-life/LAEzYFWc5Ag0QA",
    portraitKind: "life_portrait",
    portraitKindLabel: "Life portrait",
    portraitNote: "Authenticated portrait created during Nathanael Greene’s lifetime.",
    portraitRights: "Peale died in 1827; the 1783 painting is public domain. The supplied 2,400 × 3,000 JPEG is identified on Wikimedia Commons as a faithful reproduction of this two-dimensional public-domain work and marked free of known copyright restrictions (Public Domain Mark).",
  },
};
